INSERT INTO EMPLOYEE (USERNAME,NAME,SURNAME,TYPE,STATE) VALUES ('USERNAME1', 'NOMBRE1', 'APELLIDOS1', 'INTERNAL',0);
INSERT INTO EMPLOYEE (USERNAME,NAME,SURNAME,TYPE,STATE) VALUES ('USERNAME2', 'NOMBRE2', 'APELLIDOS2', 'INTERNAL',1);
INSERT INTO EMPLOYEE (USERNAME,NAME,SURNAME,TYPE,STATE) VALUES ('USERNAME3', 'NOMBRE3', 'APELLIDOS3', 'EXTERNAL',0);
INSERT INTO EMPLOYEE (USERNAME,NAME,SURNAME,TYPE,STATE) VALUES ('USERNAME4', 'NOMBRE4', 'APELLIDOS4', 'EXTERNAL',1);